### ISSUE TITLE
Prevent steam-rolling

### ISSUE THREAD

**Issue by kalekundert** [kxgames/seacow#2]
- Have cities revert to opponent if your army leaves too soon
- "Happiness" resource, like in Civ
  - seems a bit gimmicky
  - but also an effective way to increase the cost of expansion
- Militia army type
  - Cheap armies that can only be used for defense.
- Limited number of armies (e.g. 1-2)

**Comment by alexmitchell** [comment]
(from email) Call to Arms action. Triggers a draft to generate basic soldier quickly and cheaply at any city. Techs/policies (e.g. mandatory military service) can improve stats of new units. Only available during war time. Some kind of negative for generating too many? (e.g. unhappiness? Protests? Maybe economy takes a hit temporarily in addition to the resource cost. Of course policies could modulate the effect.) RONTAP has something in this direction with militia if I remember correctly.

**Comment by alexmitchell** [comment]
Clarification of "happiness" in Civ. The effect that is most interesting for us is that happiness is a cost function loosely based on empire size.  Rapid expansion generates more unhappiness. Too much unhappiness cripples the productivity of the economy. The player cannot take more than a few cities in the early or mid game before the penalty becomes too heavy a burden and they have to pause. (By late game, its much easier to divert resources to increase happiness. Early/mid game is difficult). This also applies to expansion by building new cities.

I'm not exactly a fan of the way Civ does it (but maybe bc I'm still, and probably always will be, a Civ noob... haha). I'm okay with a cost for military conquest, but I don't like that building new cities is such a pain in the butt.

How about a cost associated with how culturally similar any city is to the players culture? If you capture someone else's city, you have to pay a heavy price because it's so culturally dissimilar. Part of the assimilation process is the culture of the city realigning to the new owner's culture.

I'm also thinking the same thing can be applied to organic growth. Far flung colony cities are more expensive to control to start with because they are isolated from the rest of the empire. The flip side is that expanding near one's own empire is relatively easy because the region near one's territory is already "buttered up" to join. Would be funny to make it such that being a more aggressive military player means it's harder to expand into neutral territory (via organic growth) because your population has also been aggressive the locals too much.
